services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL','pg_isready -U myuser -d mydatabase']
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - 'PORT=8080'
      - 'DB_URL=jdbc:postgresql://postgres:5432/mydatabase'
      - 'DB_USERNAME=myuser'
      - 'DB_PASSWORD=secret'
      - 'ADMIN_USERNAME=admin'
      - 'ADMIN_PASSWORD=admin123'
    ports:
      - '8080:8080'

volumes:
  postgres_data: